# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('type', models.SmallIntegerField(choices=[(1, '主库'), (2, '从库')], verbose_name='数据库类型')),
                ('username', models.CharField(max_length=64, verbose_name='账号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('port', models.IntegerField(verbose_name='端口号')),
            ],
        ),
    ]
