# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb1', '0004_auto_20170621_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department1',
            name='name',
            field=models.CharField(max_length=225, null=True, verbose_name='备注'),
        ),
    ]
