# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb1', '0007_auto_20170621_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department1',
            name='name',
        ),
    ]
