# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb1', '0008_remove_department1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='department1',
            name='name',
            field=models.CharField(default='', max_length=225, verbose_name='备注'),
        ),
    ]
