# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department1',
            name='master_ip',
            field=models.GenericIPAddressField(blank=True, default='', null=True),
        ),
    ]
