# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb1', '0002_auto_20170717_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='department1',
            name='master_port',
            field=models.IntegerField(blank=True, null=True, verbose_name='主库端口号'),
        ),
    ]
